### PR TITLE
Switch to dockerhub mirror

### PR DESCRIPTION
**Pull request by mdeggies**
Instead of using dockerhub (which will enforce rate limiting on anonymous image pulls starting Nov 1st), we're moving projects to our mirror at `docker.mirror.hashicorp.services`.

### CODE REVIEW

**Comment by acidprime** [comment]
@mdeggies Awesome, It looks like we are mirroring everything. That said, I can't merge this as is. The action also pulls the image during build time in the Github Action it's self here https://github.com/hashicorp/learn-inspec/blob/master/action.yml#L27. So I would want to update it there as well.

**Comment by acidprime** [comment]
I can make the change in this branch if you don't have time , just let me know

**Comment by acidprime** [comment]
Updated manually, merging.

**Comment by mdeggies** [comment]
Images used within github actions don't require any changes, but you are welcome to use them there if you want :) 
Thanks for updating this!

**Pull request merged**
